### ISSUE TITLE
Just does not do anything

### ISSUE THREAD

**Issue by raveren** [imyuyu/FileSyncPlugin#4]
Latest version with latest version of PHPStorm:

<img width="1862" height="945" alt="Image" src="https://github.com/user-attachments/assets/c546c06d-6af6-4a2d-ab5c-98c631b6a3eb" />

The icons don't even load and I get ~8 null pointer exceptions simillar to this one:

```
ConsoleRemoveAction#presentation@FileSync (org.imyuyu.idea.plugins.filesync.actions.toolbar.ConsoleRemoveAction), actionId=FileSync.ConsoleRemoveAction, text='Remove Current Tab'

java.lang.NullPointerException: can't get project from event!
	at org.imyuyu.idea.plugins.filesync.utils.Utils.getPlugin(Utils.kt:56)
	at org.imyuyu.idea.plugins.filesync.actions.toolbar.ConsoleRemoveAction.update(ConsoleRemoveAction.kt:18)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.updateAction$lambda$2(ActionUtil.kt:265)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.updateAction(ActionUtil.kt:273)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performDumbAwareUpdate(ActionUtil.kt:234)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$updateAction$success$1$1$1.invoke(ActionUpdater.kt:508)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$updateAction$success$1$1$1.invoke(ActionUpdater.kt:507)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.callAction$lambda$2(ActionUpdater.kt:157)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater.computeOnEdt$lambda$10(ActionUpdater.kt:187)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$computeOnEdt$deferred$1.invokeSuspend$lambda$0(ActionUpdater.kt:435)
	at com.intellij.openapi.application.ActionsKt.runReadAction$lambda$3(actions.kt:25)
	at com.intellij.platform.locking.impl.NestedLocksThreadingSupport.runReadAction(NestedLocksThreadingSupport.kt:784)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:1038)
	at com.intellij.openapi.application.ActionsKt.runReadAction(actions.kt:25)
	at com.intellij.openapi.actionSystem.impl.ActionUpdater$computeOnEdt$deferred$1.invokeSuspend(ActionUpdater.kt:434)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at com.intellij.openapi.actionSystem.impl.AltEdtDispatcher.dispatch$lambda$0(Utils.kt:1234)
	at com.intellij.openapi.actionSystem.impl.AltEdtDispatcher.runOwnQueueBlockingAndSwitchBackToEDT(Utils.kt:1257)
	at com.intellij.openapi.actionSystem.impl.Utils$expandActionGroupSuspend$2.invokeSuspend(Utils.kt:299)
	at com.intellij.openapi.actionSystem.impl.Utils$expandActionGroupSuspend$2.invoke(Utils.kt)
	at com.intellij.openapi.actionSystem.impl.Utils$expandActionGroupSuspend$2.invoke(Utils.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:44)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:166)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.openapi.actionSystem.impl.Utils.expandActionGroupSuspend(Utils.kt:283)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl$updateActionsImpl$job$1.invokeSuspend(ActionToolbarImpl.kt:947)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl$updateActionsImpl$job$1.invoke(ActionToolbarImpl.kt)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl$updateActionsImpl$job$1.invoke(ActionToolbarImpl.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startCoroutineUndispatched(Undispatched.kt:20)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:360)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:134)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:52)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsImpl(ActionToolbarImpl.kt:943)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.access$updateActionsImpl(ActionToolbarImpl.kt:87)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl$1.updateActionsImpl(ActionToolbarImpl.kt:164)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater$MyUpdateRunnable.run(ToolbarUpdater.kt:156)
	at com.intellij.openapi.actionSystem.impl.ToolbarUpdater.updateActions(ToolbarUpdater.kt:71)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsWithoutLoadingIcon(ActionToolbarImpl.kt:927)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsImmediately(ActionToolbarImpl.kt:921)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsImmediately(ActionToolbarImpl.kt:900)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.updateActionsOnAdd(ActionToolbarImpl.kt:292)
	at com.intellij.openapi.actionSystem.impl.ActionToolbarImpl.addNotify(ActionToolbarImpl.kt:286)
	at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4847)
	at java.desktop/java.awt.Container.addImpl(Container.java:1150)
	at java.desktop/java.awt.Container.add(Container.java:1001)
	at com.intellij.openapi.wm.impl.content.ToolWindowContentUi.ensureSelectedContentVisible(ToolWindowContentUi.java:345)
	at com.intellij.openapi.wm.impl.content.ToolWindowContentUi$1.selectionChanged(ToolWindowContentUi.java:194)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at com.intellij.util.EventDispatcher.dispatchVoidMethod(EventDispatcher.java:120)
	at com.intellij.util.EventDispatcher.lambda$doCreateMulticaster$1(EventDispatcher.java:85)
	at jdk.proxy2/jdk.proxy2.$Proxy203.selectionChanged(Unknown Source)
	at com.intellij.ui.content.impl.ContentManagerImpl.fireSelectionChanged(ContentManagerImpl.java:647)
	at com.intellij.ui.content.impl.ContentManagerImpl.addSelectedContent(ContentManagerImpl.java:466)
	at com.intellij.ui.content.impl.ContentManagerImpl.setSelectedContent(ContentManagerImpl.java:557)
	at com.intellij.ui.content.impl.ContentManagerImpl.setSelectedContentCB(ContentManagerImpl.java:521)
	at com.intellij.ui.content.impl.ContentManagerImpl.setSelectedContentCB(ContentManagerImpl.java:509)
	at com.intellij.ui.content.impl.ContentManagerImpl.setSelectedContentCB(ContentManagerImpl.java:585)
	at com.intellij.ui.content.impl.ContentManagerImpl.setSelectedContent(ContentManagerImpl.java:590)
	at com.intellij.ui.content.impl.ContentManagerImpl.doAddContent(ContentManagerImpl.java:214)
	at com.intellij.ui.content.impl.ContentManagerImpl.addContent(ContentManagerImpl.java:175)
	at org.imyuyu.idea.plugins.filesync.ui.ThreadConsoleToolWindowFactory.createToolWindowContent(ThreadConsoleToolWindowFactory.kt:32)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentIfNeeded(ToolWindowImpl.kt:703)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.scheduleContentInitializationIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:683)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doShowWindow(ToolWindowManagerImpl.kt:1095)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl(ToolWindowManagerImpl.kt:1031)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activateToolWindow$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:727)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activateToolWindow$intellij_platform_ide_impl$default(ToolWindowManagerImpl.kt:694)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activated$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:2331)
	at com.intellij.openapi.wm.impl.SquareAnActionButton.setSelected(SquareStripeButton.kt:361)
	at com.intellij.openapi.actionSystem.ToggleAction.actionPerformed(ToggleAction.java:62)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:243)
	at com.intellij.openapi.actionSystem.impl.ActionButton.lambda$performAction$2(ActionButton.java:222)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.performWithActionCallbacks(ActionManagerImpl.kt:1163)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:221)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:532)
	at java.desktop/java.awt.Component.processEvent(Component.java:6438)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5043)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4871)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4963)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4577)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4518)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2810)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4871)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:783)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:728)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:755)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:753)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:752)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:595)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:540)
	at com.intellij.ide.IdeEventQueue._dispatchEvent$lambda$16(IdeEventQueue.kt:479)
	at com.intellij.platform.locking.impl.NestedLocksThreadingSupport.doRunWriteIntentReadAction(NestedLocksThreadingSupport.kt:666)
	at com.intellij.platform.locking.impl.NestedLocksThreadingSupport.runPreventiveWriteIntentReadAction(NestedLocksThreadingSupport.kt:640)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:479)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$12$lambda$11$lambda$10$lambda$9(IdeEventQueue.kt:313)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:865)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$12$lambda$11$lambda$10(IdeEventQueue.kt:312)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$3(IdeEventQueue.kt:974)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:118)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:974)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$12(IdeEventQueue.kt:307)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:347)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by imyuyu** [comment]
Can you provide a specific version? eg: 2025.2

**Comment by raveren** [comment]
Yes, that's right 2025.2

<img width="491" height="330" alt="Image" src="https://github.com/user-attachments/assets/25103f32-4909-4815-b32d-52a91d8a21a6" />

**Comment by imyuyu** [comment]
> Yes, that's right 2025.2
> 
> <img alt="Image" width="491" height="330" src="https://private-user-images.githubusercontent.com/364220/475946754-25103f32-4909-4815-b32d-52a91d8a21a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTQ2NDU4MjYsIm5iZiI6MTc1NDY0NTUyNiwicGF0aCI6Ii8zNjQyMjAvNDc1OTQ2NzU0LTI1MTAzZjMyLTQ5MDktNDgxNS1iMzJkLTUyYTkxZDhhMjFhNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgwOFQwOTMyMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMGFhY2M0YmUyMDUzODZmYTQ0MjdkOWI5NTYwOGYxOWZhNTU0ZmUwMDczMjFjNzcxOTQyNGNkNmQyYjcxN2Y3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.k20sE6tQu4Z0HNcldgPh4gDlBW0ApQrK2Pa7CbX6ZUE">

Tks, I'll fix it.

**Comment by imyuyu** [comment]
Fixed in version 1.15.4

**Comment by raveren** [comment]
Well, there's no more errors, but it does nothing, can you tell me what I'm doing wrong:

<img width="2228" height="1104" alt="Image" src="https://github.com/user-attachments/assets/c8693971-19a2-4d00-bfb7-bcf2e4c39782" />

saving a file does nothing, and the 
>Selection excluded from synchronization

is output when I press the green "run" button

**Comment by imyuyu** [comment]
#

> Well, there's no more errors, but it does nothing, can you tell me what I'm doing wrong:
> 
> <img alt="Image" width="2000" height="1104" src="https://private-user-images.githubusercontent.com/364220/480845046-c8693971-19a2-4d00-bfb7-bcf2e4c39782.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTYwNTA0NDEsIm5iZiI6MTc1NjA1MDE0MSwicGF0aCI6Ii8zNjQyMjAvNDgwODQ1MDQ2LWM4NjkzOTcxLTE5YTItNGQwMC1iZmI3LWJjZjJlNGMzOTc4Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwODI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDgyNFQxNTQyMjFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMWQ0ZmQwY2Y0Yjk5YjRjNGYzNTAyZWZlZjRhMTQ1ZjVkZGIxNjljMzRjYzdmN2U0NjBlMmFhNmVkNmQzMWU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.cB2vPGUfpD6pAcVPtuMxJujlxCX7R7E1scxjLmkN3g8">
> saving a file does nothing, and the
> 
> > Selection excluded from synchronization
> 
> is output when I press the green "run" button

Well, looks like the support for wsl is not very good, can you verify the non-wsl directory?

**Comment by raveren** [comment]
yeah it's still not working, it's not working if I open a directory in the non-wsl part of windows either

<img width="1495" height="902" alt="Image" src="https://github.com/user-attachments/assets/501299e3-2674-4db8-93c9-e9c2ac249bd7" />

**Comment by imyuyu** [comment]
Okay, thank you for your feedback. It seems that PHP files are not supported. I will reopen this issue

**Comment by imyuyu** [comment]
Hi.
I can't reproduce this issue, below is my project

<img width="1384" height="992" alt="Image" src="https://github.com/user-attachments/assets/eec8b413-d466-4f00-aaa0-5d25f39f7b67" />

below is my configuration

<img width="1384" height="992" alt="Image" src="https://github.com/user-attachments/assets/8079bfb4-be24-48cd-af8b-bb814408b68a" />

as you can see, everything works fine.

Attention！**If you do not open any files before clicking `Synchronize all opened`, you may not be able to synchronize any files (console output: `Selection excluded from synchronization`). In this case, please try using `Synchronize all` or select the files you want to synchronize and execute `Synchronize this`**

**Comment by raveren** [comment]
Well, ok, it started to work when I right-clicked and chose "Synchronize this" and it started syncing that one file when I pressed the green go button in the panel.

Clicking synchronize all on a medium sized project starts syncing and "usually" freezes all PHPStorm instances while it's running - for 5+ minutes for a medium-sized project.

And then the files don't keep syncing, THE REASON why I picked this plugin up is I assumed from the description that it syncs files whenever I save them so I don't need a manual action, because I can do this easily with a shell command.

So in conclusion:

1. there's no way for the user to find out that additionally to setting this plugin up, one must also go to the file rightclick menu to initiate syncing
2. the UI hangs when the files are syncing
3. the plugin has no purpose to exist in the first place if it does not sync automatically

**Comment by imyuyu** [comment]
> Well, ok, it started to work when I right-clicked and chose "Synchronize this" and it started syncing that one file when I pressed the green go button in the panel.
> 
> Clicking synchronize all on a medium sized project starts syncing and "usually" freezes all PHPStorm instances while it's running - for 5+ minutes for a medium-sized project.
> 
> And then the files don't keep syncing, THE REASON why I picked this plugin up is I assumed from the description that it syncs files whenever I save them so I don't need a manual action, because I can do this easily with a shell command.
> 
> So in conclusion:
> 
> 1. there's no way for the user to find out that additionally to setting this plugin up, one must also go to the file rightclick menu to initiate syncing
> 2. the UI hangs when the files are syncing
> 3. the plugin has no purpose to exist in the first place if it does not sync automatically

Oh, as you mentioned, this plugin does have these issues. The reason is that it was originally designed to synchronize Java code, which is meant to synchronize the class files generated after compilation. However, Java compilation may not be automatic, so automatic synchronization was not considered.

Regarding the UI freezing issue when synchronizing a large number of files, I will open a separate issue.

Thank you!

**Comment by raveren** [comment]
Thanks for the OSS project!

Its main selling point could be that it would finally be a painless solution to developing a project and its composer dependencies at the same time.

**Comment by imyuyu** [comment]
> Thanks for the OSS project!
> 
> Its main selling point could be that it would finally be a painless solution to developing a project and its composer dependencies at the same time.

Tks!

Yes, that's what we do. We have standard products and some custom projects. This plugin allows custom developers to focus only on the code they need to modify locally (which is usually much smaller than the complete project). It's like writing a plugin for Idea, where you only need to focus on the plugin code itself.

**Comment by raveren** [comment]
But to make that happen - the plugin should "automatically save files into multiple locations".

Anyway, good luck, if this ever happens, I'd be ecstatic to pick it up again 👍

**Comment by imyuyu** [comment]
> But to make that happen - the plugin should "automatically save files into multiple locations".
> 
> Anyway, good luck, if this ever happens, I'd be ecstatic to pick it up again 👍

This is a great idea, and I'll try to implement it if I have the time.
